update workflows according to checklist
zowe/zowe-cli-cics-plugin pull request #138
Opened 2023-05-05 15:57 UTC by ATorrise

Action | Description
-- | -- | 
#1 | add stale bot
#2 | add auto-comment bot on labels 
#3 | add issue template (Bug, Feature)  
#4 | add PR Template
#5 | add question redirect
#6 | update all workflows to remove deprecation warnings
#7 | remove Node 14 from workflow matrix

2023-05-08 16:34 UTC, zFernand0 requested changes
LGTM! 😋 
just one comment though 😅

2023-05-08 16:34 UTC, zFernand0 commented on .github/workflows/changelog.yml
Can we also update `awharn/check_changelog_action@v0.0.2` to `v1`?

2023-05-09 03:59 UTC, t1m0thyj approved these changes

2023-05-09 13:06 UTC, zFernand0 requested changes
LGTM, the only thing is that we have a node12 being setup for the linter.yml file
Can we update that to `lts/*`?

2023-05-09 13:06 UTC, zFernand0 commented on .github/workflows/changelog.yml
> -      - zowe-v1-lts
there may be other workflows in this repo that could use the same update.
but I don't think it particularly matters for this branch or until we create a zowe-v2-lts branch

2023-05-09 13:06 UTC, zFernand0 commented on .github/workflows/linter.yml
>          node-version: 12.x
we should probably use `lts/*` here
And please, don't forget to also update the step name 😋

2023-05-10 14:47 UTC, zFernand0 approved these changes

2023-05-11 16:03 UTC, merged