versioning changes
zowe/zowe-cli-cics-plugin pull request #141
Opened 2023-05-05 18:46 UTC by ATorrise

Action | Description
-- | --									
#6 | [update all workflows to remove deprecation warnings](https://github.com/zowe/zowe-cli-web-help-generator/pull/35/files), [octorelease updates](https://github.com/zowe/zowe-cli/pull/1712)										
#7 | remove Node 14 from workflow matrix

2023-05-08 14:40 UTC, zFernand0 commented on .github/workflows/changelog.yml
Can we change the `awharn/check_changelog_action@v0.0.2` to `v1`?
- `awharn/check_changelog_action@v0.0.2` -> `awharn/check_changelog_action@v1`

2023-05-08 14:46 UTC, zFernand0 commented on .github/workflows/codeql.yml
>        uses: github/codeql-action/init@v1
forgot to mention that both the init and the annalyze should be moved to v2 if possible 😋 
https://github.com/github/codeql-action#usage

2023-05-09 04:01 UTC, t1m0thyj requested changes

2023-05-09 04:01 UTC, t1m0thyj commented on .github/workflows/zowe-cli-plugin.yml
Please update `actions/upload-artifact` to v3 to fix the remaining warning for this workflow

2023-05-10 14:32 UTC, zFernand0 approved these changes

2023-05-10 14:33 UTC, zFernand0 commented
I noticed that some workflows have hte `zowe-v1-lts`, but I approved it since this is not a huge concern at the moment 😋

2023-05-11 16:07 UTC, t1m0thyj approved these changes

2023-05-11 16:41 UTC, zFernand0 approved these changes

2023-05-11 16:41 UTC, merged